export const HANDLE_QUERY:String = "HANDLE_QUERY";
export const HANDLE_MEDIA_TYPE:String = "HANDLE_MEDIA_TYPE";
export const HANDLE_COLLECTION_LINK:String = "HANDLE_COLLECTION_LINK";
export const HANDLE_COLLECTION_INFO:String = "HANDLE_COLLECTION_INFO";